export const ActionTypes = {
    APP: 'APP',
    LOGIN: 'LOGIN',
    UPDATE_CREDS: 'UPDATE_CREDS',
    LOGOUT: 'LOGOUT',
    UPDATE_RUNNING: 'UPDATE_RUNNING',
    UPDATE_BIKING: 'UPDATE_BIKING',
    UPDATE_SWIMMING: 'UPDATE_SWIMMING',
    UPDATE_CURLS: 'UPDATE_CURLS',
    UPDATE_BENCH_PRESS: 'UPDATE_BENCH_PRESS',
    UPDATE_DEAD_LIFT: 'UPDATE_DEAD_LIFT',
    UPDATE_SQUATS: 'UPDATE_SQUATS',
    UPDATE_PUSH_UPS: 'UPDATE_PUSH_UPS',
    UPDATE_PULL_UPS: 'UPDATE_PULL_UPS',
    UPDATE_SIT_UPS: 'UPDATE_SIT_UPS',
    SUBMIT_WORKOUTS: 'SUBMIT_WORKOUTS'
};